spring:
  application:
    name: csc311finalcapstoneprojectgroup04

eureka:
  client:
    #set register to false as we are going to enable it if the user is hosting
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      host-name: "Max"
      current-players: "0"
      active-game: true
